In [53]:
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras.models import load_model

import pickle

In [54]:
model=load_model('model.h5')

In [55]:
with open('ohe.pkl','rb')as file:
    label_encoder_geo=pickle.load(file)
with open('scaler.pkl','rb')as file:
    label_scaler_encoder=pickle.load(file)
with open('label_encoder_gender.pkl','rb')as file:
    label_gender_encoder=pickle.load(file)


In [56]:
input_person = {
    "RowNumber": 9999,
    "CustomerId": 15876543,
    "Surname": "Sharma",
    "CreditScore": 720,
    "Geography": "Germany",
    "Gender": "Male",
    "Age": 45,
    "Tenure": 5,
    "Balance": 120000.50,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 0,
    "EstimatedSalary": 95000.25
}


In [57]:
geo_encoded=label_encoder_geo.transform([[input_person['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\udemy_genai\ann_implementation\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [58]:
input_person_df=pd.DataFrame([input_person])
input_person_df

RowNumber  CustomerId Surname  CreditScore Geography Gender  Age  Tenure  \
0       9999    15876543  Sharma          720   Germany   Male   45       5   

    Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0  120000.5              2          1               0         95000.25

In [59]:
input_person_df['Gender']=label_gender_encoder.transform(input_person_df['Gender'])
input_person_df

RowNumber  CustomerId Surname  CreditScore Geography  Gender  Age  Tenure  \
0       9999    15876543  Sharma          720   Germany       1   45       5   

    Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0  120000.5              2          1               0         95000.25

In [60]:
# input_person_df=pd.concat([input_person_df.reset_index(drop=True),geo_encoded_df],axis=1)

In [61]:
input_person_df

RowNumber  CustomerId Surname  CreditScore Geography  Gender  Age  Tenure  \
0       9999    15876543  Sharma          720   Germany       1   45       5   

    Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0  120000.5              2          1               0         95000.25

In [62]:
input_person_df=pd.concat([input_person_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_person_df

RowNumber  CustomerId Surname  CreditScore  Gender  Age  Tenure   Balance  \
0       9999    15876543  Sharma          720       1   45       5  120000.5   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0              2          1               0         95000.25   

   Geography_France  Geography_Germany  Geography_Spain  
0               0.0                1.0              0.0

In [63]:
input_person_df=input_person_df.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [64]:
input_person_df

CreditScore  Gender  Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0          720       1   45       5  120000.5              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               0         95000.25               0.0                1.0   

   Geography_Spain  
0              0.0

In [66]:
#scaling the input data
input_scaled=label_scaler_encoder.transform(input_person_df)
input_scaled

array([[ 7.09342564e-01,  9.13247552e-01,  5.80155774e-01,
        -1.34471949e-03,  7.02856186e-01,  8.08436154e-01,
         6.49202671e-01, -1.02583358e+00, -9.44276978e-02,
        -9.98501123e-01,  1.72572313e+00, -5.76388018e-01]])

In [67]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 231ms/step


array([[0.23248298]], dtype=float32)

In [69]:
prediction_prob=prediction[0][0]
prediction

array([[0.23248298]], dtype=float32)

In [70]:
if prediction_prob>0.5:
    print("yes")
else:
    print("No")

No
